sudo: true
language: python
matrix:
  include:
    - python: 2.7
      arch: arm64
    - python: 2.7
      arch: amd64
    - python: 3.3
      arch: arm64
    - python: 3.3
      arch: amd64
    - python: 3.4
      arch: arm64
    - python: 3.4
      arch: amd64
install:
  - python setup.py install
  - python -m pip install pytest nose
  - pip install whoosh
script:
  - pytest
  - nosetests
